In [30]:
import numpy as np

In [31]:
array = np.arange(0,10)

In [32]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
cond = array > 5

In [34]:
cond2 = (array > 5) & (array < 9)
cond2

array([False, False, False, False, False, False,  True,  True,  True,
       False])

In [35]:
cond2 = (array > 5) | (array < 9)
cond2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])