In [1]:
import numpy as np

In [4]:
array = np.arange(1,13)

In [5]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
array.shape

(12,)

In [10]:
remodelado = array.reshape(2,6)
remodelado

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
print(type(remodelado))

<class 'numpy.ndarray'>


In [11]:
remodelado**2

array([[  1,   4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121, 144]])

In [12]:
remodelado+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22]])

In [13]:
remodelado

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [14]:
remodelado = array.reshape(3,4)
remodelado

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
remodelado.shape

(3, 4)

In [16]:
remodelado = array.reshape(2,2,3)
remodelado

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
remodelado[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
remodelado[0][1]

array([4, 5, 6])